export const labels = {
	game: 'game',
	sceneFinish: 'sceneFinish',
	scene: 'scene',
	sceneBg: 'sceneBg',
	customers: 'customers',
	customer: 'customer',
	world: 'world',
	humanOne: 'human-1',
	humanTwo: 'human-2',
	humanThree: 'human-3',
	humanFour: 'human-4',
	humanFive: 'human-5',
	cow: 'cow',
	cows: 'cows',
	placeCow: 'placeCow',
	milk: 'milk',
	cars: 'cars',
	car: 'car',
	carLeft: 'carLeft',
	carRight: 'carRight',
	carTop: 'carTop',
	carBottom: 'carBottom',
	carLevelOne: 'carLevelOne',
	carLevelTwo: 'carLevelTwo',
	carLevelThree: 'carLevelThree',
	carLevelFour: 'carLevelFour',
	carContainer: 'carContainer',
	truckBtn: 'truckBtn',
	cowBtn: 'cowBtn',
	tutorHand: 'tutorHand',
	sceneStart: 'sceneStart',
	fail: 'fail'
};

export const customersNames = [
	'human-1',
	'human-2',
	'human-3',
	'human-4',
	'human-5',
	'human-6'
];

export const cowsNames = [
	'cow-1',
	'cow-1',
	'cow-1',
	'cow-1'
];

export const cowMilkNames = [
	'cowMilk-1',
	'cowMilk-2',
	'cowMilk-3',
	'cowMilk-4',
	'cowMilk-5'
];

export const carsNames = [
	{
		car: 'car-1',
		carMilk: 'car-1-milk',
		carRight: 'car-1-right',
		carRightMilk: 'car-1-milk-right',
		carTop: 'car-1-top',
		carTopMilk: 'car-1-milk-top',
		carBottom: 'car-1-bottom',
		carBottomMilk: 'car-1-milk-bottom',
		name: labels.carLevelOne
	},
	{
		car: 'car-2',
		carMilk: 'car-2-milk',
		carRight: 'car-2-right',
		carRightMilk: 'car-2-milk-right',
		carTop: 'car-2-top',
		carTopMilk: 'car-2-milk-top',
		carBottom: 'car-2-bottom',
		carBottomMilk: 'car-2-milk-bottom',
		name: labels.carLevelTwo
	},
	{
		car: 'car-3',
		carMilk: 'car-3-milk',
		carRight: 'car-3-right',
		carRightMilk: 'car-3-milk-right',
		carTop: 'car-3-top',
		carTopMilk: 'car-3-milk-top',
		carBottom: 'car-3-bottom',
		carBottomMilk: 'car-3-milk-bottom',
		name: labels.carLevelThree
	},
	{
		car: 'car-4',
		carMilk: 'car-4-milk',
		carRight: 'car-4-right',
		carRightMilk: 'car-4-milk-right',
		carTop: 'car-4-top',
		carTopMilk: 'car-4-milk-top',
		carBottom: 'car-4-bottom',
		carBottomMilk: 'car-4-milk-bottom',
		name: labels.carLevelFour
	}
];

export const gameStages = {
	stageStart: 'stageStart',
	stageOne: 'stageOne',
	stageTwo: 'stageTwo',
	stageThree: 'stageThree',
	stageFour: 'stageFour',
	stageFinish: 'stageFinish'
};


export const assetsNames = {
	cow1: 'cow-1',
	cow2: 'cow-2',
	cow3: 'cow-3',
	cow4: 'cow-4',
	bg: 'bg',
	car1Bottom: 'car-1-bottom',
	car1MilkBottom: 'car-1-milk-bottom',
	car1MilkRight: 'car-1-milk-right',
	car1MilkTop: 'car-1-milk-top',
	car1Milk: 'car-1-milk',
	car1Right: 'car-1-right',
	car1Top: 'car-1-top',
	car1: 'car-1',
	car2Bottom: 'car-2-bottom',
	car2MilkBottom: 'car-2-milk-bottom',
	car2MilkRight: 'car-2-milk-right',
	car2MilkTop: 'car-2-milk-top',
	car2Milk: 'car-2-milk',
	car2Right: 'car-2-right',
	car2Top: 'car-2-top',
	car2: 'car-2',
	car3Bottom: 'car-3-bottom',
	car3MilkBottom: 'car-3-milk-bottom',
	car3MilkRight: 'car-3-milk-right',
	car3MilkTop: 'car-3-milk-top',
	car3Milk: 'car-3-milk',
	car3Right: 'car-3-right',
	car3Top: 'car-3-top',
	car3: 'car-3',
	car4Bottom: 'car-4-bottom',
	car4MilkBottom: 'car-4-milk-bottom',
	car4MilkRight: 'car-4-milk-right',
	car4MilkTop: 'car-4-milk-top',
	car4Milk: 'car-4-milk',
	car4Right: 'car-4-right',
	car4Top: 'car-4-top',
	car4: 'car-4',
	chatbubble: 'chatBubble',
	cow1: 'cow-1',
	cow2: 'cow-2',
	cow3: 'cow-3',
	cow4: 'cow-4',
	cowbtn: 'cowBtn',
	cowmilk1: 'cowMilk-1',
	cowmilk2: 'cowMilk-2',
	cowmilk3: 'cowMilk-3',
	cowmilk4: 'cowMilk-4',
	cowmilk5: 'cowMilk-5',
	download: 'download',
	fontsPinksans: 'fonts/PinkSans',
	hand: 'hand',
	heart: 'heart',
	human1: 'human-1',
	human2: 'human-2',
	human3: 'human-3',
	human4: 'human-4',
	human5: 'human-5',
	human6: 'human-6',
	milk: 'milk',
	placecow: 'placeCow',
	soundoff: 'soundOff',
	soundon: 'soundOn',
	taskfield: 'taskField',
	truckbtn: 'truckBtn',
	cow1: 'cow-1',
	cow2: 'cow-2',
	cow3: 'cow-3',
	cow4: 'cow-4',
	cows: 'cows',
	cows: 'cows',
	soundBg: 'bg',
	soundCow: 'cow',
	soundCowmilking: 'cowMilking',
	soundFail: 'fail',
	soundFail1: 'fail1',
	soundTruck: 'truck',
	soundUpgrade: 'upgrade',
};
